-- Deploy user

BEGIN;

-- XXX Add DDLs here.
CREATE TABLE user (
	id SERIAL PRIMARY KEY,
    name VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

COMMIT;
