-- Deploy user_agent

BEGIN;

-- XXX Add DDLs here.
CREATE TABLE user_agent (
	id SERIAL PRIMARY KEY,
    user_agent VARCHAR(256) NOT NULL,
    created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
COLLATE='utf8_unicode_ci'
ENGINE=InnoDB;

COMMIT;
